// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: example.proto

package examplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImplicitEnum_MyEnum int32

const (
	ImplicitEnum_MY_ENUM_UNSPECIFIED ImplicitEnum_MyEnum = 0
	ImplicitEnum_MY_ENUM_VALUE_1     ImplicitEnum_MyEnum = 1
	ImplicitEnum_MY_ENUM_VALUE_2     ImplicitEnum_MyEnum = 2
)

// Enum value maps for ImplicitEnum_MyEnum.
var (
	ImplicitEnum_MyEnum_name = map[int32]string{
		0: "MY_ENUM_UNSPECIFIED",
		1: "MY_ENUM_VALUE_1",
		2: "MY_ENUM_VALUE_2",
	}
	ImplicitEnum_MyEnum_value = map[string]int32{
		"MY_ENUM_UNSPECIFIED": 0,
		"MY_ENUM_VALUE_1":     1,
		"MY_ENUM_VALUE_2":     2,
	}
)

func (x ImplicitEnum_MyEnum) Enum() *ImplicitEnum_MyEnum {
	p := new(ImplicitEnum_MyEnum)
	*p = x
	return p
}

func (x ImplicitEnum_MyEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImplicitEnum_MyEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[0].Descriptor()
}

func (ImplicitEnum_MyEnum) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[0]
}

func (x ImplicitEnum_MyEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImplicitEnum_MyEnum.Descriptor instead.
func (ImplicitEnum_MyEnum) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0, 0}
}

type OptionalEnum_MyEnum int32

const (
	OptionalEnum_MY_ENUM_UNSPECIFIED OptionalEnum_MyEnum = 0
	OptionalEnum_MY_ENUM_VALUE_1     OptionalEnum_MyEnum = 1
	OptionalEnum_MY_ENUM_VALUE_2     OptionalEnum_MyEnum = 2
)

// Enum value maps for OptionalEnum_MyEnum.
var (
	OptionalEnum_MyEnum_name = map[int32]string{
		0: "MY_ENUM_UNSPECIFIED",
		1: "MY_ENUM_VALUE_1",
		2: "MY_ENUM_VALUE_2",
	}
	OptionalEnum_MyEnum_value = map[string]int32{
		"MY_ENUM_UNSPECIFIED": 0,
		"MY_ENUM_VALUE_1":     1,
		"MY_ENUM_VALUE_2":     2,
	}
)

func (x OptionalEnum_MyEnum) Enum() *OptionalEnum_MyEnum {
	p := new(OptionalEnum_MyEnum)
	*p = x
	return p
}

func (x OptionalEnum_MyEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptionalEnum_MyEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[1].Descriptor()
}

func (OptionalEnum_MyEnum) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[1]
}

func (x OptionalEnum_MyEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptionalEnum_MyEnum.Descriptor instead.
func (OptionalEnum_MyEnum) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1, 0}
}

type RepeatedEnum_MyEnum int32

const (
	RepeatedEnum_MY_ENUM_UNSPECIFIED RepeatedEnum_MyEnum = 0
	RepeatedEnum_MY_ENUM_VALUE_1     RepeatedEnum_MyEnum = 1
	RepeatedEnum_MY_ENUM_VALUE_2     RepeatedEnum_MyEnum = 2
)

// Enum value maps for RepeatedEnum_MyEnum.
var (
	RepeatedEnum_MyEnum_name = map[int32]string{
		0: "MY_ENUM_UNSPECIFIED",
		1: "MY_ENUM_VALUE_1",
		2: "MY_ENUM_VALUE_2",
	}
	RepeatedEnum_MyEnum_value = map[string]int32{
		"MY_ENUM_UNSPECIFIED": 0,
		"MY_ENUM_VALUE_1":     1,
		"MY_ENUM_VALUE_2":     2,
	}
)

func (x RepeatedEnum_MyEnum) Enum() *RepeatedEnum_MyEnum {
	p := new(RepeatedEnum_MyEnum)
	*p = x
	return p
}

func (x RepeatedEnum_MyEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepeatedEnum_MyEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[2].Descriptor()
}

func (RepeatedEnum_MyEnum) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[2]
}

func (x RepeatedEnum_MyEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepeatedEnum_MyEnum.Descriptor instead.
func (RepeatedEnum_MyEnum) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{2, 0}
}

type ImplicitEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField ImplicitEnum_MyEnum `protobuf:"varint,1,opt,name=my_field,json=myField,proto3,enum=example.ImplicitEnum_MyEnum" json:"my_field,omitempty"`
}

func (x *ImplicitEnum) Reset() {
	*x = ImplicitEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImplicitEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplicitEnum) ProtoMessage() {}

func (x *ImplicitEnum) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplicitEnum.ProtoReflect.Descriptor instead.
func (*ImplicitEnum) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *ImplicitEnum) GetMyField() ImplicitEnum_MyEnum {
	if x != nil {
		return x.MyField
	}
	return ImplicitEnum_MY_ENUM_UNSPECIFIED
}

type OptionalEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField *OptionalEnum_MyEnum `protobuf:"varint,1,opt,name=my_field,json=myField,proto3,enum=example.OptionalEnum_MyEnum,oneof" json:"my_field,omitempty"`
}

func (x *OptionalEnum) Reset() {
	*x = OptionalEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalEnum) ProtoMessage() {}

func (x *OptionalEnum) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalEnum.ProtoReflect.Descriptor instead.
func (*OptionalEnum) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *OptionalEnum) GetMyField() OptionalEnum_MyEnum {
	if x != nil && x.MyField != nil {
		return *x.MyField
	}
	return OptionalEnum_MY_ENUM_UNSPECIFIED
}

type RepeatedEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []RepeatedEnum_MyEnum `protobuf:"varint,1,rep,packed,name=my_field,json=myField,proto3,enum=example.RepeatedEnum_MyEnum" json:"my_field,omitempty"`
}

func (x *RepeatedEnum) Reset() {
	*x = RepeatedEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedEnum) ProtoMessage() {}

func (x *RepeatedEnum) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedEnum.ProtoReflect.Descriptor instead.
func (*RepeatedEnum) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{2}
}

func (x *RepeatedEnum) GetMyField() []RepeatedEnum_MyEnum {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []bool `protobuf:"varint,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedBool) Reset() {
	*x = RepeatedBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedBool) ProtoMessage() {}

func (x *RepeatedBool) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedBool.ProtoReflect.Descriptor instead.
func (*RepeatedBool) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{3}
}

func (x *RepeatedBool) GetMyField() []bool {
	if x != nil {
		return x.MyField
	}
	return nil
}

type ImplicitUint32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField uint32 `protobuf:"varint,1,opt,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *ImplicitUint32) Reset() {
	*x = ImplicitUint32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImplicitUint32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplicitUint32) ProtoMessage() {}

func (x *ImplicitUint32) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplicitUint32.ProtoReflect.Descriptor instead.
func (*ImplicitUint32) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{4}
}

func (x *ImplicitUint32) GetMyField() uint32 {
	if x != nil {
		return x.MyField
	}
	return 0
}

type OptionalUint32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField *uint32 `protobuf:"varint,1,opt,name=my_field,json=myField,proto3,oneof" json:"my_field,omitempty"`
}

func (x *OptionalUint32) Reset() {
	*x = OptionalUint32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalUint32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalUint32) ProtoMessage() {}

func (x *OptionalUint32) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalUint32.ProtoReflect.Descriptor instead.
func (*OptionalUint32) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{5}
}

func (x *OptionalUint32) GetMyField() uint32 {
	if x != nil && x.MyField != nil {
		return *x.MyField
	}
	return 0
}

type RepeatedUint32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []uint32 `protobuf:"varint,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedUint32) Reset() {
	*x = RepeatedUint32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedUint32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedUint32) ProtoMessage() {}

func (x *RepeatedUint32) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedUint32.ProtoReflect.Descriptor instead.
func (*RepeatedUint32) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{6}
}

func (x *RepeatedUint32) GetMyField() []uint32 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedInt32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []int32 `protobuf:"varint,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedInt32) Reset() {
	*x = RepeatedInt32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedInt32) ProtoMessage() {}

func (x *RepeatedInt32) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedInt32.ProtoReflect.Descriptor instead.
func (*RepeatedInt32) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{7}
}

func (x *RepeatedInt32) GetMyField() []int32 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedSint32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []int32 `protobuf:"zigzag32,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedSint32) Reset() {
	*x = RepeatedSint32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedSint32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedSint32) ProtoMessage() {}

func (x *RepeatedSint32) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedSint32.ProtoReflect.Descriptor instead.
func (*RepeatedSint32) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{8}
}

func (x *RepeatedSint32) GetMyField() []int32 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedUint64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []uint64 `protobuf:"varint,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedUint64) Reset() {
	*x = RepeatedUint64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedUint64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedUint64) ProtoMessage() {}

func (x *RepeatedUint64) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedUint64.ProtoReflect.Descriptor instead.
func (*RepeatedUint64) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{9}
}

func (x *RepeatedUint64) GetMyField() []uint64 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []int64 `protobuf:"varint,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedInt64) Reset() {
	*x = RepeatedInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedInt64) ProtoMessage() {}

func (x *RepeatedInt64) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedInt64.ProtoReflect.Descriptor instead.
func (*RepeatedInt64) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{10}
}

func (x *RepeatedInt64) GetMyField() []int64 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedSint64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []int64 `protobuf:"zigzag64,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedSint64) Reset() {
	*x = RepeatedSint64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedSint64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedSint64) ProtoMessage() {}

func (x *RepeatedSint64) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedSint64.ProtoReflect.Descriptor instead.
func (*RepeatedSint64) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{11}
}

func (x *RepeatedSint64) GetMyField() []int64 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedFixed32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []uint32 `protobuf:"fixed32,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedFixed32) Reset() {
	*x = RepeatedFixed32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedFixed32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedFixed32) ProtoMessage() {}

func (x *RepeatedFixed32) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedFixed32.ProtoReflect.Descriptor instead.
func (*RepeatedFixed32) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{12}
}

func (x *RepeatedFixed32) GetMyField() []uint32 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedSfixed32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []int32 `protobuf:"fixed32,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedSfixed32) Reset() {
	*x = RepeatedSfixed32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedSfixed32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedSfixed32) ProtoMessage() {}

func (x *RepeatedSfixed32) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedSfixed32.ProtoReflect.Descriptor instead.
func (*RepeatedSfixed32) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{13}
}

func (x *RepeatedSfixed32) GetMyField() []int32 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []float32 `protobuf:"fixed32,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedFloat) Reset() {
	*x = RepeatedFloat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedFloat) ProtoMessage() {}

func (x *RepeatedFloat) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedFloat.ProtoReflect.Descriptor instead.
func (*RepeatedFloat) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{14}
}

func (x *RepeatedFloat) GetMyField() []float32 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedFixed64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []uint64 `protobuf:"fixed64,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedFixed64) Reset() {
	*x = RepeatedFixed64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedFixed64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedFixed64) ProtoMessage() {}

func (x *RepeatedFixed64) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedFixed64.ProtoReflect.Descriptor instead.
func (*RepeatedFixed64) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{15}
}

func (x *RepeatedFixed64) GetMyField() []uint64 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedSfixed64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []int64 `protobuf:"fixed64,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedSfixed64) Reset() {
	*x = RepeatedSfixed64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedSfixed64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedSfixed64) ProtoMessage() {}

func (x *RepeatedSfixed64) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedSfixed64.ProtoReflect.Descriptor instead.
func (*RepeatedSfixed64) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{16}
}

func (x *RepeatedSfixed64) GetMyField() []int64 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedDouble struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []float64 `protobuf:"fixed64,1,rep,packed,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedDouble) Reset() {
	*x = RepeatedDouble{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedDouble) ProtoMessage() {}

func (x *RepeatedDouble) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedDouble.ProtoReflect.Descriptor instead.
func (*RepeatedDouble) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{17}
}

func (x *RepeatedDouble) GetMyField() []float64 {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedBytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField [][]byte `protobuf:"bytes,1,rep,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedBytes) Reset() {
	*x = RepeatedBytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedBytes) ProtoMessage() {}

func (x *RepeatedBytes) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedBytes.ProtoReflect.Descriptor instead.
func (*RepeatedBytes) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{18}
}

func (x *RepeatedBytes) GetMyField() [][]byte {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []string `protobuf:"bytes,1,rep,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedString) Reset() {
	*x = RepeatedString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedString) ProtoMessage() {}

func (x *RepeatedString) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedString.ProtoReflect.Descriptor instead.
func (*RepeatedString) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{19}
}

func (x *RepeatedString) GetMyField() []string {
	if x != nil {
		return x.MyField
	}
	return nil
}

type ImplicitSubmessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField *ImplicitSubmessage_Sub `protobuf:"bytes,1,opt,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *ImplicitSubmessage) Reset() {
	*x = ImplicitSubmessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImplicitSubmessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplicitSubmessage) ProtoMessage() {}

func (x *ImplicitSubmessage) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplicitSubmessage.ProtoReflect.Descriptor instead.
func (*ImplicitSubmessage) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{20}
}

func (x *ImplicitSubmessage) GetMyField() *ImplicitSubmessage_Sub {
	if x != nil {
		return x.MyField
	}
	return nil
}

type OptionalSubmessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField *OptionalSubmessage_Sub `protobuf:"bytes,1,opt,name=my_field,json=myField,proto3,oneof" json:"my_field,omitempty"`
}

func (x *OptionalSubmessage) Reset() {
	*x = OptionalSubmessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalSubmessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalSubmessage) ProtoMessage() {}

func (x *OptionalSubmessage) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalSubmessage.ProtoReflect.Descriptor instead.
func (*OptionalSubmessage) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{21}
}

func (x *OptionalSubmessage) GetMyField() *OptionalSubmessage_Sub {
	if x != nil {
		return x.MyField
	}
	return nil
}

type RepeatedSubmessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField []*RepeatedSubmessage_Sub `protobuf:"bytes,1,rep,name=my_field,json=myField,proto3" json:"my_field,omitempty"`
}

func (x *RepeatedSubmessage) Reset() {
	*x = RepeatedSubmessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedSubmessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedSubmessage) ProtoMessage() {}

func (x *RepeatedSubmessage) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedSubmessage.ProtoReflect.Descriptor instead.
func (*RepeatedSubmessage) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{22}
}

func (x *RepeatedSubmessage) GetMyField() []*RepeatedSubmessage_Sub {
	if x != nil {
		return x.MyField
	}
	return nil
}

type ImplicitSubmessage_Sub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubmessageField []uint32 `protobuf:"varint,1,rep,packed,name=submessage_field,json=submessageField,proto3" json:"submessage_field,omitempty"`
}

func (x *ImplicitSubmessage_Sub) Reset() {
	*x = ImplicitSubmessage_Sub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImplicitSubmessage_Sub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplicitSubmessage_Sub) ProtoMessage() {}

func (x *ImplicitSubmessage_Sub) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplicitSubmessage_Sub.ProtoReflect.Descriptor instead.
func (*ImplicitSubmessage_Sub) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{20, 0}
}

func (x *ImplicitSubmessage_Sub) GetSubmessageField() []uint32 {
	if x != nil {
		return x.SubmessageField
	}
	return nil
}

type OptionalSubmessage_Sub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubmessageField []uint32 `protobuf:"varint,1,rep,packed,name=submessage_field,json=submessageField,proto3" json:"submessage_field,omitempty"`
}

func (x *OptionalSubmessage_Sub) Reset() {
	*x = OptionalSubmessage_Sub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalSubmessage_Sub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalSubmessage_Sub) ProtoMessage() {}

func (x *OptionalSubmessage_Sub) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalSubmessage_Sub.ProtoReflect.Descriptor instead.
func (*OptionalSubmessage_Sub) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{21, 0}
}

func (x *OptionalSubmessage_Sub) GetSubmessageField() []uint32 {
	if x != nil {
		return x.SubmessageField
	}
	return nil
}

type RepeatedSubmessage_Sub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubmessageField []uint32 `protobuf:"varint,1,rep,packed,name=submessage_field,json=submessageField,proto3" json:"submessage_field,omitempty"`
}

func (x *RepeatedSubmessage_Sub) Reset() {
	*x = RepeatedSubmessage_Sub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedSubmessage_Sub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedSubmessage_Sub) ProtoMessage() {}

func (x *RepeatedSubmessage_Sub) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedSubmessage_Sub.ProtoReflect.Descriptor instead.
func (*RepeatedSubmessage_Sub) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{22, 0}
}

func (x *RepeatedSubmessage_Sub) GetSubmessageField() []uint32 {
	if x != nil {
		return x.SubmessageField
	}
	return nil
}

var File_example_proto protoreflect.FileDescriptor

var file_example_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x94, 0x01, 0x0a, 0x0c, 0x49, 0x6d, 0x70,
	0x6c, 0x69, 0x63, 0x69, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x37, 0x0a, 0x08, 0x6d, 0x79, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x49, 0x6d, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x45, 0x6e,
	0x75, 0x6d, 0x2e, 0x4d, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x22, 0x4b, 0x0a, 0x06, 0x4d, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x17, 0x0a, 0x13,
	0x4d, 0x59, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x59, 0x5f, 0x45, 0x4e, 0x55, 0x4d,
	0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x31, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x59,
	0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x32, 0x10, 0x02, 0x22,
	0xa6, 0x01, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d,
	0x12, 0x3c, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x4d, 0x79, 0x45, 0x6e, 0x75, 0x6d,
	0x48, 0x00, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x88, 0x01, 0x01, 0x22, 0x4b,
	0x0a, 0x06, 0x4d, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x59, 0x5f, 0x45,
	0x4e, 0x55, 0x4d, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x59, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x56, 0x41, 0x4c,
	0x55, 0x45, 0x5f, 0x31, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x59, 0x5f, 0x45, 0x4e, 0x55,
	0x4d, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x32, 0x10, 0x02, 0x42, 0x0b, 0x0a, 0x09, 0x5f,
	0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x37, 0x0a, 0x08, 0x6d, 0x79, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6e,
	0x75, 0x6d, 0x2e, 0x4d, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x22, 0x4b, 0x0a, 0x06, 0x4d, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x17, 0x0a, 0x13,
	0x4d, 0x59, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x59, 0x5f, 0x45, 0x4e, 0x55, 0x4d,
	0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x31, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x59,
	0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x32, 0x10, 0x02, 0x22,
	0x29, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6c, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x08, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x2b, 0x0a, 0x0e, 0x49, 0x6d,
	0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x3d, 0x0a, 0x0e, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x1e, 0x0a, 0x08, 0x6d, 0x79, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x07, 0x6d,
	0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6d, 0x79,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x2b, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x22, 0x2a, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49,
	0x6e, 0x74, 0x33, 0x32, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22,
	0x2b, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x11, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x2b, 0x0a, 0x0e,
	0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x19,
	0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x2a, 0x0a, 0x0d, 0x52, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x79,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x79,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x2b, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x53, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x12, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x22, 0x2c, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69,
	0x78, 0x65, 0x64, 0x33, 0x32, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x07, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x22, 0x2d, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x66, 0x69, 0x78,
	0x65, 0x64, 0x33, 0x32, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0f, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22,
	0x2a, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x02, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x2c, 0x0a, 0x0f, 0x52,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x19,
	0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x06,
	0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x2d, 0x0a, 0x10, 0x52, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x10, 0x52,
	0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x2b, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x79,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x6d, 0x79,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x2a, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x22, 0x2b, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x82,
	0x01, 0x0a, 0x12, 0x49, 0x6d, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x53, 0x75, 0x62, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2e, 0x49, 0x6d, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x53, 0x75, 0x62, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x1a, 0x30, 0x0a, 0x03, 0x53, 0x75, 0x62, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x0f, 0x73, 0x75, 0x62, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x12, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x53, 0x75, 0x62, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x6d, 0x79,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53,
	0x75, 0x62, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x48, 0x00, 0x52,
	0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x88, 0x01, 0x01, 0x1a, 0x30, 0x0a, 0x03, 0x53,
	0x75, 0x62, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0f, 0x73, 0x75,
	0x62, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x12, 0x52,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x75, 0x62, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3a, 0x0a, 0x08, 0x6d, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x52, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x75, 0x62, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x53, 0x75, 0x62, 0x52, 0x07, 0x6d, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x30, 0x0a,
	0x03, 0x53, 0x75, 0x62, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0f,
	0x73, 0x75, 0x62, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42,
	0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData = file_example_proto_rawDesc
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_proto_rawDescData)
	})
	return file_example_proto_rawDescData
}

var file_example_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_example_proto_goTypes = []interface{}{
	(ImplicitEnum_MyEnum)(0),       // 0: example.ImplicitEnum.MyEnum
	(OptionalEnum_MyEnum)(0),       // 1: example.OptionalEnum.MyEnum
	(RepeatedEnum_MyEnum)(0),       // 2: example.RepeatedEnum.MyEnum
	(*ImplicitEnum)(nil),           // 3: example.ImplicitEnum
	(*OptionalEnum)(nil),           // 4: example.OptionalEnum
	(*RepeatedEnum)(nil),           // 5: example.RepeatedEnum
	(*RepeatedBool)(nil),           // 6: example.RepeatedBool
	(*ImplicitUint32)(nil),         // 7: example.ImplicitUint32
	(*OptionalUint32)(nil),         // 8: example.OptionalUint32
	(*RepeatedUint32)(nil),         // 9: example.RepeatedUint32
	(*RepeatedInt32)(nil),          // 10: example.RepeatedInt32
	(*RepeatedSint32)(nil),         // 11: example.RepeatedSint32
	(*RepeatedUint64)(nil),         // 12: example.RepeatedUint64
	(*RepeatedInt64)(nil),          // 13: example.RepeatedInt64
	(*RepeatedSint64)(nil),         // 14: example.RepeatedSint64
	(*RepeatedFixed32)(nil),        // 15: example.RepeatedFixed32
	(*RepeatedSfixed32)(nil),       // 16: example.RepeatedSfixed32
	(*RepeatedFloat)(nil),          // 17: example.RepeatedFloat
	(*RepeatedFixed64)(nil),        // 18: example.RepeatedFixed64
	(*RepeatedSfixed64)(nil),       // 19: example.RepeatedSfixed64
	(*RepeatedDouble)(nil),         // 20: example.RepeatedDouble
	(*RepeatedBytes)(nil),          // 21: example.RepeatedBytes
	(*RepeatedString)(nil),         // 22: example.RepeatedString
	(*ImplicitSubmessage)(nil),     // 23: example.ImplicitSubmessage
	(*OptionalSubmessage)(nil),     // 24: example.OptionalSubmessage
	(*RepeatedSubmessage)(nil),     // 25: example.RepeatedSubmessage
	(*ImplicitSubmessage_Sub)(nil), // 26: example.ImplicitSubmessage.Sub
	(*OptionalSubmessage_Sub)(nil), // 27: example.OptionalSubmessage.Sub
	(*RepeatedSubmessage_Sub)(nil), // 28: example.RepeatedSubmessage.Sub
}
var file_example_proto_depIdxs = []int32{
	0,  // 0: example.ImplicitEnum.my_field:type_name -> example.ImplicitEnum.MyEnum
	1,  // 1: example.OptionalEnum.my_field:type_name -> example.OptionalEnum.MyEnum
	2,  // 2: example.RepeatedEnum.my_field:type_name -> example.RepeatedEnum.MyEnum
	26, // 3: example.ImplicitSubmessage.my_field:type_name -> example.ImplicitSubmessage.Sub
	27, // 4: example.OptionalSubmessage.my_field:type_name -> example.OptionalSubmessage.Sub
	28, // 5: example.RepeatedSubmessage.my_field:type_name -> example.RepeatedSubmessage.Sub
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImplicitEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImplicitUint32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalUint32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedUint32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedInt32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedSint32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedUint64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedSint64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedFixed32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedSfixed32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedFloat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedFixed64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedSfixed64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedDouble); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedBytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImplicitSubmessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalSubmessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedSubmessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImplicitSubmessage_Sub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalSubmessage_Sub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedSubmessage_Sub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_example_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_example_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_example_proto_msgTypes[21].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		EnumInfos:         file_example_proto_enumTypes,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_rawDesc = nil
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
